# Generated by Django 4.1 on 2023-04-04 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nome_categoria', models.CharField(max_length=50)),
                ('data_ora_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_ora_modifica', models.DateTimeField(auto_now=True)),
                ('attiva', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorie',
            },
        ),
        migrations.CreateModel(
            name='Dispensa',
            fields=[
                ('id_dispensa', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nome_dispensa', models.CharField(max_length=50)),
                ('condivisa', models.BooleanField(default=False)),
                ('attiva', models.BooleanField(default=True)),
                ('data_ora_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_ora_modifica', models.DateTimeField(auto_now=True)),
                ('inserito_da', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inserito_da_dispensa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prodotti',
            fields=[
                ('id_prodotto', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nome_prodotto', models.CharField(max_length=50)),
                ('marca_prodotto', models.CharField(blank=True, max_length=50, null=True)),
                ('descrizione_prodotto', models.CharField(blank=True, max_length=200, null=True)),
                ('prezzo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('attivo', models.BooleanField(default=True)),
                ('scadenza_default', models.IntegerField(blank=True, null=True)),
                ('data_ora_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_ora_modifica', models.DateTimeField(auto_now=True)),
                ('id_categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_categoria_prodotto', to='dispense.categorie')),
                ('id_dispensa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_dispensa_prodotto', to='dispense.dispensa')),
                ('inserito_da', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inserito_da_prodotto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prodotto',
                'verbose_name_plural': 'Prodotti',
            },
        ),
        migrations.CreateModel(
            name='Elementi',
            fields=[
                ('id_elemento', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('data_scadenza', models.DateField()),
                ('data_ora_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_ora_modifica', models.DateTimeField(auto_now=True)),
                ('inserito_da', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inserito_da_elemento', to=settings.AUTH_USER_MODEL)),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodotto_elemento', to='dispense.prodotti')),
            ],
            options={
                'verbose_name': 'Elemento',
                'verbose_name_plural': 'Elementi',
            },
        ),
        migrations.CreateModel(
            name='DispensaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifiche', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=False)),
                ('condivisa_da', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condivisa_da_disp_user', to=settings.AUTH_USER_MODEL)),
                ('id_dispensa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_dispensa_disp_user', to='dispense.dispensa')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_user_disp_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dispensa',
            name='user',
            field=models.ManyToManyField(related_name='user', through='dispense.DispensaUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categorie',
            name='id_dispensa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_dispensa_categoria', to='dispense.dispensa'),
        ),
        migrations.AddField(
            model_name='categorie',
            name='inserito_da',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inserito_da_categoria', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='prodotti',
            constraint=models.UniqueConstraint(fields=('id_prodotto', 'id_dispensa'), name='unique_prodotto_dispensa'),
        ),
        migrations.AddConstraint(
            model_name='categorie',
            constraint=models.UniqueConstraint(fields=('id_categoria', 'id_dispensa'), name='unique_categoria_dispensa'),
        ),
    ]
