# Generated by Django 4.1 on 2023-04-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispense', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispensa',
            options={'verbose_name': 'Dispensa', 'verbose_name_plural': 'Dispense'},
        ),
        migrations.AlterModelOptions(
            name='dispensauser',
            options={'verbose_name': 'DispensaUser', 'verbose_name_plural': 'DispensaUsers'},
        ),
        migrations.AddConstraint(
            model_name='dispensauser',
            constraint=models.UniqueConstraint(fields=('id_user', 'id_dispensa'), name='unique_disp_user'),
        ),
    ]
