# Generated by Django 4.1 on 2023-04-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispense', '0003_remove_categorie_unique_categoria_dispensa_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='categorie',
            name='unique_categoria_dispensa',
        ),
        migrations.AddConstraint(
            model_name='categorie',
            constraint=models.UniqueConstraint(fields=('id_dispensa', 'nome_categoria'), name='unique_categoria_dispensa'),
        ),
    ]
