# Generated by Django 4.1 on 2023-04-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispense', '0004_remove_categorie_unique_categoria_dispensa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotti',
            name='id_prodotto',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
