# Generated by Django 4.1 on 2023-04-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispense', '0005_alter_prodotti_id_prodotto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotti',
            name='id_prodotto',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
