# Generated by Django 4.1 on 2023-04-14 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispense', '0006_alter_prodotti_id_prodotto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elementi',
            old_name='prodotto',
            new_name='id_prodotto',
        ),
    ]
